import './style.css';
import * as XLSX from 'xlsx';
import seedProducts from './seed-products.json';

const DB='tb-bisma-db', STORE='app', KEY='state';
const initial=()=>({version:1,products:seedProducts,transactions:[],debts:[],suppliers:[],expenses:[],returns:[],stockLogs:[],orders:[],customers:[],requests:[],cashClosings:[],pendingCarts:[],activity:[],settings:{store:'TB Bisma',dana:'085198580017',seabank:'901869157871',owner:'BISMA PUTRA RASTIKA'},cart:[]});
let state, page='dashboard', query='';
const uid=(p='x')=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const money=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
const now=()=>new Date().toISOString();
const date=v=>v?new Date(v).toLocaleString('id-ID'):'-';

function dbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function load(){const db=await dbOpen();state=await new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(KEY);r.onsuccess=()=>res(r.result||initial());r.onerror=()=>rej(r.error)});render()}
async function save(msg){const db=await dbOpen();await new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(state,KEY);r.onsuccess=res;r.onerror=()=>rej(r.error)});if(msg)toast(msg)}
function log(action){state.activity.unshift({id:uid('log'),at:now(),action});state.activity=state.activity.slice(0,1000)}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),2200)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const activeProducts=()=>state.products.filter(p=>p.active!==false);
const salesTotal=()=>state.transactions.reduce((a,t)=>a+Number(t.total||0),0);
const profitTotal=()=>state.transactions.reduce((a,t)=>a+Number(t.profit||0),0)-state.expenses.reduce((a,e)=>a+Number(e.amount||0),0);

const nav=[['dashboard','Dashboard'],['products','Data Barang'],['cashier','Kasir'],['stock','Stok Masuk'],['debts','Piutang / Bon'],['payment','Pembayaran'],['history','Riwayat'],['reports','Laporan'],['suppliers','Supplier'],['expenses','Pengeluaran'],['returns','Retur'],['opname','Stok Opname'],['orders','Pesanan Supplier'],['customers','Pelanggan'],['requests','Permintaan Barang'],['cash','Tutup Kas'],['backup','Backup & Data']];
function shell(content){return `<div class="app"><header class="topbar"><img src="/assets/icon.png"><div><h1>TB Bisma</h1><small>Offline • Data tersimpan di perangkat</small></div></header><div class="layout"><aside class="sidebar">${nav.map(n=>`<button class="navbtn ${page===n[0]?'active':''}" data-page="${n[0]}">${n[1]}</button>`).join('')}</aside><main class="content">${content}</main></div><nav class="bottomnav">${[['dashboard','Beranda'],['products','Barang'],['cashier','Kasir'],['debts','Bon'],['reports','Laporan']].map(n=>`<button data-page="${n[0]}">${n[1]}</button>`).join('')}</nav></div>`}
function render(){let c=views[page]?views[page]():views.dashboard();document.querySelector('#app').innerHTML=shell(c);bind()}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;query='';render()});document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>actions[b.dataset.act]?.(b.dataset.id,b));}
const title=(t,buttons='')=>`<div class="section-title"><h2>${t}</h2><div>${buttons}</div></div>`;
const btn=(label,act,cls='primary',id='')=>`<button class="btn ${cls}" data-act="${act}" ${id?`data-id="${id}"`:''}>${label}</button>`;
const table=(heads,rows)=>`<div class="tablewrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${heads.length}" class="empty">Belum ada data</td></tr>`}</tbody></table></div>`;

const views={
 dashboard(){const low=activeProducts().filter(p=>p.stock<=p.minStock);return title('Dashboard')+`<div class="grid"><div class="card stat">Total Barang<b>${activeProducts().length}</b></div><div class="card stat">Stok Menipis<b class="low">${low.length}</b></div><div class="card stat">Penjualan<b>${money(salesTotal())}</b></div><div class="card stat">Estimasi Profit<b>${money(profitTotal())}</b></div></div><div class="toolbar">${btn('Transaksi Baru','goCash')}${btn('Tambah Barang','addProduct','')}${btn('Stok Masuk','addStock','')}${btn('Tambah Bon','addDebt','')}</div><div class="card"><h3>Stok Hampir Habis</h3>${low.slice(0,12).map(p=>`<p><b>${esc(p.name)}</b> ${esc(p.variant)} — <span class="low">${p.stock} ${p.unit}</span></p>`).join('')||'<div class="empty">Belum ada stok menipis</div>'}</div>`},
 products(){let ps=activeProducts().filter(p=>(p.name+' '+p.variant+' '+p.category+' '+p.aliases).toLowerCase().includes(query.toLowerCase()));return title('Data Barang',btn('+ Tambah Barang','addProduct'))+`<div class="toolbar"><input class="input" id="search" placeholder="Cari nama, ukuran, kategori, alias..." value="${esc(query)}"></div>`+table(['Foto','Nama','Kategori','Ukuran','Stok','Modal','Jual','Aksi'],ps.map(p=>`<tr><td><img class="product-img" src="${p.image||'/assets/icon.png'}"></td><td><b>${esc(p.name)}</b>${p.favorite?' ★':''}<br><small>${esc(p.aliases||'')}</small></td><td><span class="pill">${esc(p.category)}</span></td><td>${esc(p.variant)}</td><td class="${p.stock<=p.minStock?'low':'oktxt'}">${p.stock} ${esc(p.unit)}</td><td>${money(p.cost)}</td><td>${money(p.price)}</td><td>${btn('Edit','editProduct','',p.id)} ${btn('Nonaktifkan','disableProduct','danger',p.id)}</td></tr>`).join(''))},
 cashier(){const cart=state.cart||[];let total=cart.reduce((a,i)=>a+i.qty*i.price,0);return title('Kasir / Transaksi',btn('Pendingkan','pendingCart',''))+`<div class="toolbar"><button class="btn primary" data-act="pickProduct">+ Tambah Barang</button>${state.pendingCarts.length?btn(`Buka Pending (${state.pendingCarts.length})`,'openPending',''):''}</div>`+table(['Barang','Qty','Harga','Total',''],cart.map(i=>`<tr><td>${esc(i.name)}<br><small>${esc(i.variant)}</small></td><td><button class="btn" data-act="cartMinus" data-id="${i.id}">−</button> ${i.qty} <button class="btn" data-act="cartPlus" data-id="${i.id}">+</button></td><td>${money(i.price)}</td><td>${money(i.qty*i.price)}</td><td>${btn('Hapus','cartRemove','danger',i.id)}</td></tr>`).join(''))+`<div class="card" style="margin-top:14px"><h3>Total: ${money(total)}</h3><div class="formgrid"><label>Bayar<input id="pay" type="number" class="input" value="${total}"></label><label>Metode<select id="method" class="input"><option>Tunai</option><option>QRIS</option><option>DANA</option><option>SeaBank</option><option>Bon</option></select></label><label class="full">Nama pelanggan (opsional)<input id="buyer" class="input"></label></div><div class="toolbar">${btn('Simpan Transaksi','checkout')}${btn('Kosongkan','clearCart','danger')}</div></div>`},
 stock(){return title('Stok Masuk',btn('+ Catat Stok Masuk','addStock'))+logTable('stok')},
 debts(){return title('Piutang / Bon',btn('+ Tambah Bon','addDebt'))+table(['Pelanggan','Tanggal','Barang/Catatan','Total','Sudah Bayar','Sisa','Status','Aksi'],state.debts.map(d=>{let s=d.total-d.paid;return `<tr><td>${esc(d.customer)}</td><td>${date(d.date)}</td><td>${esc(d.note)}</td><td>${money(d.total)}</td><td>${money(d.paid)}</td><td class="${s>0?'low':'oktxt'}">${money(s)}</td><td>${s<=0?'Lunas':d.paid?'Cicilan':'Belum Lunas'}</td><td>${s>0?btn('Tambah Bayar','payDebt','',d.id):''}</td></tr>`}).join(''))},
 payment(){return title('Pembayaran')+`<div class="paycard"><div class="card"><h3>QRIS</h3><img class="qris" src="/assets/qris.jpg"></div><div class="card"><h3>SeaBank</h3><h2>901869157871</h2><p>a.n. BISMA PUTRA RASTIKA</p>${btn('Salin Nomor','copySea')}</div><div class="card"><h3>DANA</h3><h2>085198580017</h2><p>BISMA PUTRA RASTIKA</p>${btn('Salin Nomor','copyDana')}</div></div>`},
 history(){return title('Riwayat Transaksi')+table(['No. Transaksi','Tanggal','Pelanggan','Metode','Total','Profit','Aksi'],state.transactions.map(t=>`<tr><td>${t.no}</td><td>${date(t.date)}</td><td>${esc(t.customer||'Umum')}</td><td>${esc(t.method)}</td><td>${money(t.total)}</td><td>${money(t.profit)}</td><td>${btn('Batalkan','cancelTx','danger',t.id)}</td></tr>`).join(''))},
 reports(){const stockCost=activeProducts().reduce((a,p)=>a+p.stock*p.cost,0),stockSell=activeProducts().reduce((a,p)=>a+p.stock*p.price,0),debt=state.debts.reduce((a,d)=>a+Math.max(0,d.total-d.paid),0);return title('Laporan')+`<div class="grid"><div class="card stat">Nilai Modal Stok<b>${money(stockCost)}</b></div><div class="card stat">Nilai Jual Stok<b>${money(stockSell)}</b></div><div class="card stat">Total Piutang<b>${money(debt)}</b></div><div class="card stat">Profit Bersih<b>${money(profitTotal())}</b></div></div><div class="card" style="margin-top:14px"><h3>Pemeriksaan Data</h3><p>Stok minus: <b>${state.products.filter(p=>p.stock<0).length}</b></p><p>Harga jual di bawah modal: <b>${state.products.filter(p=>p.price&&p.price<p.cost).length}</b></p><p>Barang tanpa kategori: <b>${state.products.filter(p=>!p.category).length}</b></p><p>Barang tanpa harga jual: <b>${state.products.filter(p=>!p.price).length}</b></p></div>`},
 suppliers(){return generic('Supplier','suppliers',['name','phone','note'],['Nama','No. HP','Catatan'])},
 expenses(){return title('Pengeluaran Toko',btn('+ Tambah','addExpense'))+table(['Tanggal','Keterangan','Kategori','Nominal'],state.expenses.map(e=>`<tr><td>${date(e.date)}</td><td>${esc(e.note)}</td><td>${esc(e.category)}</td><td>${money(e.amount)}</td></tr>`).join(''))},
 returns(){return title('Retur Barang',btn('+ Catat Retur','addReturn'))+table(['Tanggal','Jenis','Barang','Qty','Alasan'],state.returns.map(r=>`<tr><td>${date(r.date)}</td><td>${esc(r.type)}</td><td>${esc(r.product)}</td><td>${r.qty}</td><td>${esc(r.reason)}</td></tr>`).join(''))},
 opname(){return title('Stok Opname',btn('Mulai Opname','startOpname'))+`<div class="card"><p>Gunakan fitur ini untuk mencocokkan stok aplikasi dengan stok fisik. Selisih akan tercatat di riwayat stok.</p></div>`+logTable('opname')},
 orders(){return generic('Pesanan Supplier','orders',['item','qty','supplier','status'],['Barang','Jumlah','Supplier','Status'])},
 customers(){return generic('Data Pelanggan','customers',['name','phone','address','note'],['Nama','No. HP','Alamat','Catatan'])},
 requests(){return generic('Permintaan Barang Pelanggan','requests',['item','customer','phone','status'],['Barang','Pelanggan','No. HP','Status'])},
 cash(){return title('Tutup Kas Harian',btn('+ Tutup Kas','closeCash'))+table(['Tanggal','Kas Awal','Penjualan Tunai','Pengeluaran','Kas Seharusnya','Kas Nyata','Selisih'],state.cashClosings.map(c=>`<tr><td>${date(c.date)}</td><td>${money(c.opening)}</td><td>${money(c.cashSales)}</td><td>${money(c.expenses)}</td><td>${money(c.expected)}</td><td>${money(c.actual)}</td><td>${money(c.actual-c.expected)}</td></tr>`).join(''))},
 backup(){return title('Backup & Data')+`<div class="card"><h3>Amankan data toko</h3><div class="toolbar">${btn('Backup JSON','backupJson')}${btn('Export Excel','exportExcel','')}${btn('Pulihkan Backup','restore','')}${btn('Import Excel Barang','importExcel','')}</div><input type="file" id="fileRestore" hidden><p>Data tetap tersimpan saat aplikasi ditutup atau HP direstart. Data dapat hilang jika aplikasi dihapus atau data aplikasi dibersihkan, jadi lakukan backup rutin.</p></div><div class="card" style="margin-top:14px"><h3>Log Aktivitas</h3>${state.activity.slice(0,30).map(a=>`<p>${date(a.at)} — ${esc(a.action)}</p>`).join('')}</div>`}
};
function generic(name,key,fields,heads){return title(name,btn('+ Tambah','genericAdd','',key))+table(heads,state[key].map(x=>`<tr>${fields.map(f=>`<td>${esc(x[f])}</td>`).join('')}</tr>`).join(''))}
function logTable(kind){let xs=state.stockLogs.filter(x=>x.kind===kind);return table(['Tanggal','Barang','Perubahan','Catatan'],xs.map(x=>`<tr><td>${date(x.date)}</td><td>${esc(x.product)}</td><td>${x.qty>0?'+':''}${x.qty}</td><td>${esc(x.note)}</td></tr>`).join(''))}
function modal(html){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modalbox">${html}</div>`;m.onclick=e=>{if(e.target===m)m.remove()};document.body.append(m);return m}
function productOptions(){return activeProducts().map(p=>`<option value="${p.id}">${esc(p.name)} ${esc(p.variant)} — stok ${p.stock}</option>`).join('')}
const val=(m,id)=>m.querySelector('#'+id)?.value||'';

const actions={
 goCash(){page='cashier';render()},
 addProduct(){productForm()}, editProduct(id){productForm(state.products.find(p=>p.id===id))},
 disableProduct(id){let p=state.products.find(x=>x.id===id);if(confirm('Nonaktifkan barang ini?')){p.active=false;log('Barang dinonaktifkan: '+p.name);save('Barang dinonaktifkan');render()}},
 pickProduct(){const m=modal(`<h3>Pilih Barang</h3><input id="pq" class="input" placeholder="Cari barang..."><div id="plist"></div><div class="toolbar"><button class="btn" id="close">Tutup</button></div>`);const draw=()=>{let q=val(m,'pq').toLowerCase();m.querySelector('#plist').innerHTML=activeProducts().filter(p=>(p.name+' '+p.variant+' '+p.aliases).toLowerCase().includes(q)).slice(0,60).map(p=>`<button class="navbtn choose" data-id="${p.id}">${esc(p.name)} ${esc(p.variant)} — ${money(p.price)} — stok ${p.stock}</button>`).join('')};draw();m.querySelector('#pq').oninput=draw;m.addEventListener('click',e=>{let b=e.target.closest('.choose');if(b){let p=state.products.find(x=>x.id===b.dataset.id),i=state.cart.find(x=>x.id===p.id);if(i)i.qty++;else state.cart.push({id:p.id,name:p.name,variant:p.variant,qty:1,price:p.price,cost:p.cost});save();m.remove();render()}});m.querySelector('#close').onclick=()=>m.remove()},
 cartPlus(id){let i=state.cart.find(x=>x.id===id);i.qty++;save();render()},cartMinus(id){let i=state.cart.find(x=>x.id===id);i.qty=Math.max(1,i.qty-1);save();render()},cartRemove(id){state.cart=state.cart.filter(x=>x.id!==id);save();render()},clearCart(){if(confirm('Kosongkan keranjang?')){state.cart=[];save();render()}},
 pendingCart(){if(!state.cart.length)return toast('Keranjang masih kosong');state.pendingCarts.push({id:uid('pc'),date:now(),items:state.cart});state.cart=[];save('Transaksi dipending');render()},
 openPending(){const m=modal(`<h3>Transaksi Pending</h3>${state.pendingCarts.map(c=>`<button class="navbtn pend" data-id="${c.id}">${date(c.date)} — ${c.items.length} jenis barang</button>`).join('')}<button class="btn" id="close">Tutup</button>`);m.addEventListener('click',e=>{let b=e.target.closest('.pend');if(b){let c=state.pendingCarts.find(x=>x.id===b.dataset.id);state.cart=c.items;state.pendingCarts=state.pendingCarts.filter(x=>x.id!==c.id);save();m.remove();render()}});m.querySelector('#close').onclick=()=>m.remove()},
 checkout(){if(!state.cart.length)return toast('Keranjang kosong');let total=state.cart.reduce((a,i)=>a+i.qty*i.price,0),method=document.querySelector('#method').value,buyer=document.querySelector('#buyer').value||'Umum';for(const i of state.cart){let p=state.products.find(x=>x.id===i.id);if(p.stock<i.qty&&!confirm(`${p.name} stok kurang. Tetap lanjut?`))return;p.stock-=i.qty;state.stockLogs.unshift({id:uid(),kind:'sale',date:now(),product:p.name,qty:-i.qty,note:'Penjualan'})}let t={id:uid('trx'),no:'TRX-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+String(state.transactions.length+1).padStart(3,'0'),date:now(),customer:buyer,method,items:structuredClone(state.cart),total,profit:state.cart.reduce((a,i)=>a+i.qty*(i.price-i.cost),0)};state.transactions.unshift(t);if(method==='Bon')state.debts.unshift({id:uid('bon'),customer:buyer,date:now(),note:t.items.map(i=>i.name+' x'+i.qty).join(', '),total,paid:0});state.cart=[];log('Transaksi disimpan: '+t.no);save('Transaksi berhasil disimpan');render()},
 cancelTx(id){let t=state.transactions.find(x=>x.id===id);if(!t||!confirm('Batalkan transaksi dan kembalikan stok?'))return;t.items.forEach(i=>{let p=state.products.find(x=>x.id===i.id);if(p)p.stock+=i.qty});state.transactions=state.transactions.filter(x=>x.id!==id);log('Transaksi dibatalkan: '+t.no);save('Transaksi dibatalkan');render()},
 addStock(){simpleForm('Tambah Stok',`<label>Barang<select id="product" class="input">${productOptions()}</select></label><label>Jumlah<input id="qty" type="number" class="input" value="1"></label><label>Harga modal terbaru<input id="cost" type="number" class="input"></label><label>Catatan<input id="note" class="input"></label>`,m=>{let p=state.products.find(x=>x.id===val(m,'product')),q=+val(m,'qty');p.stock+=q;if(val(m,'cost'))p.cost=+val(m,'cost');state.stockLogs.unshift({id:uid(),kind:'stok',date:now(),product:p.name,qty:q,note:val(m,'note')||'Stok masuk'});log('Stok masuk: '+p.name+' +'+q)})},
 addDebt(){simpleForm('Tambah Piutang / Bon',`<label>Nama pelanggan<input id="customer" class="input" required></label><label>Total utang<input id="total" type="number" class="input"></label><label>Sudah titip / bayar<input id="paid" type="number" class="input" value="0"></label><label>Barang dan catatan<textarea id="note" class="input"></textarea></label>`,m=>state.debts.unshift({id:uid('bon'),customer:val(m,'customer'),total:+val(m,'total'),paid:+val(m,'paid'),note:val(m,'note'),date:now()}))},
 payDebt(id){let d=state.debts.find(x=>x.id===id),amt=+prompt('Nominal pembayaran:',d.total-d.paid);if(amt>0){d.paid+=amt;log('Pembayaran bon '+d.customer+': '+money(amt));save('Pembayaran dicatat');render()}},
 copySea(){navigator.clipboard.writeText('901869157871');toast('Nomor SeaBank disalin')},copyDana(){navigator.clipboard.writeText('085198580017');toast('Nomor DANA disalin')},
 addExpense(){simpleForm('Tambah Pengeluaran',`<label>Keterangan<input id="note" class="input"></label><label>Kategori<input id="category" class="input" placeholder="Belanja/Ongkir/Listrik/Lainnya"></label><label>Nominal<input id="amount" type="number" class="input"></label>`,m=>state.expenses.unshift({id:uid(),date:now(),note:val(m,'note'),category:val(m,'category'),amount:+val(m,'amount')}))},
 addReturn(){simpleForm('Catat Retur',`<label>Jenis<select id="type" class="input"><option>Retur Penjualan</option><option>Retur ke Supplier</option></select></label><label>Barang<select id="product" class="input">${productOptions()}</select></label><label>Jumlah<input id="qty" type="number" class="input" value="1"></label><label>Alasan<input id="reason" class="input"></label>`,m=>{let p=state.products.find(x=>x.id===val(m,'product')),q=+val(m,'qty'),type=val(m,'type');p.stock+=type==='Retur Penjualan'?q:-q;state.returns.unshift({id:uid(),date:now(),type,product:p.name,qty:q,reason:val(m,'reason')});state.stockLogs.unshift({id:uid(),kind:'return',date:now(),product:p.name,qty:type==='Retur Penjualan'?q:-q,note:type})})},
 startOpname(){simpleForm('Stok Opname',`<label>Barang<select id="product" class="input">${productOptions()}</select></label><label>Stok fisik<input id="actual" type="number" class="input"></label><label>Catatan<input id="note" class="input"></label>`,m=>{let p=state.products.find(x=>x.id===val(m,'product')),old=p.stock,actual=+val(m,'actual');p.stock=actual;state.stockLogs.unshift({id:uid(),kind:'opname',date:now(),product:p.name,qty:actual-old,note:val(m,'note')||`Sebelum ${old}, fisik ${actual}`})})},
 genericAdd(key){let configs={suppliers:[['name','Nama'],['phone','No. HP'],['note','Catatan']],orders:[['item','Barang'],['qty','Jumlah'],['supplier','Supplier'],['status','Status']],customers:[['name','Nama'],['phone','No. HP'],['address','Alamat'],['note','Catatan']],requests:[['item','Barang dicari'],['customer','Pelanggan'],['phone','No. HP'],['status','Status']]},fs=configs[key];simpleForm('Tambah Data',fs.map(f=>`<label>${f[1]}<input id="${f[0]}" class="input"></label>`).join(''),m=>{let x={id:uid(),date:now()};fs.forEach(f=>x[f[0]]=val(m,f[0]));state[key].unshift(x)})},
 closeCash(){let today=new Date().toDateString(),cashSales=state.transactions.filter(t=>new Date(t.date).toDateString()===today&&t.method==='Tunai').reduce((a,t)=>a+t.total,0),expenses=state.expenses.filter(e=>new Date(e.date).toDateString()===today).reduce((a,e)=>a+e.amount,0);simpleForm('Tutup Kas',`<label>Kas awal<input id="opening" type="number" class="input" value="0"></label><label>Penjualan tunai<input class="input" value="${cashSales}" disabled></label><label>Pengeluaran<input class="input" value="${expenses}" disabled></label><label>Kas nyata<input id="actual" type="number" class="input"></label>`,m=>{let opening=+val(m,'opening'),expected=opening+cashSales-expenses;state.cashClosings.unshift({id:uid(),date:now(),opening,cashSales,expenses,expected,actual:+val(m,'actual')})})},
 backupJson(){download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),`TB-Bisma-backup-${Date.now()}.json`)},
 exportExcel(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.products),'DATA BARANG');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.transactions.map(t=>({No:t.no,Tanggal:t.date,Pelanggan:t.customer,Metode:t.method,Total:t.total,Profit:t.profit}))),'TRANSAKSI');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.debts),'PIUTANG');XLSX.writeFile(wb,`TB-Bisma-${Date.now()}.xlsx`)},
 restore(){let i=document.querySelector('#fileRestore');i.accept='.json';i.onchange=async()=>{let obj=JSON.parse(await i.files[0].text());if(confirm('Pulihkan backup dan mengganti data sekarang?')){state=obj;await save('Backup dipulihkan');render()}};i.click()},
 importExcel(){let i=document.querySelector('#fileRestore');i.accept='.xlsx,.xls';i.onchange=async()=>{let wb=XLSX.read(await i.files[0].arrayBuffer()),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]);let added=0;for(const r of rows){let name=r['NAMA BARANG']||r['Nama Barang']||r.name;if(!name)continue;state.products.push({id:uid('p'),name,category:r.KATEGORI||r.Kategori||'LAINNYA',variant:r['UKURAN / VARIAN']||r.Ukuran||'',unit:r.SATUAN||'pcs',stock:+(r.STOK||0),minStock:5,cost:+(r['HARGA MODAL']||0),price:+(r['HARGA JUAL']||0),aliases:'',active:true,image:''});added++}log('Import Excel: '+added+' barang');await save(`${added} barang diimport`);render()};i.click()}
};
function simpleForm(name,body,onSave){const m=modal(`<h3>${name}</h3><div class="formgrid">${body}</div><div class="toolbar"><button class="btn primary" id="save">Simpan</button><button class="btn" id="close">Batal</button></div>`);m.querySelector('#close').onclick=()=>m.remove();m.querySelector('#save').onclick=async()=>{onSave(m);log(name);await save('Data disimpan');m.remove();render()}}
function productForm(p){p=p||{};const m=modal(`<h3>${p.id?'Edit':'Tambah'} Barang</h3><div class="formgrid"><label>Nama barang<input id="name" class="input" value="${esc(p.name||'')}"></label><label>Kategori<input id="category" class="input" value="${esc(p.category||'')}"></label><label>Ukuran / varian<input id="variant" class="input" value="${esc(p.variant||'')}"></label><label>Satuan<select id="unit" class="input">${['pcs','box','batang','meter','kg','set','kaleng','botol'].map(x=>`<option ${p.unit===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Stok<input id="stock" type="number" class="input" value="${p.stock||0}"></label><label>Batas minimum<input id="minStock" type="number" class="input" value="${p.minStock??5}"></label><label>Harga modal<input id="cost" type="number" class="input" value="${p.cost||0}"></label><label>Harga jual<input id="price" type="number" class="input" value="${p.price||0}"></label><label>Harga grosir<input id="wholesalePrice" type="number" class="input" value="${p.wholesalePrice||0}"></label><label>Minimal grosir<input id="wholesaleMin" type="number" class="input" value="${p.wholesaleMin||0}"></label><label class="full">Alias nama barang<input id="aliases" class="input" value="${esc(p.aliases||'')}"></label><label class="full">Foto produk<input id="image" type="file" accept="image/*" capture="environment" class="input"></label><label><input id="favorite" type="checkbox" ${p.favorite?'checked':''}> Barang favorit</label></div><div class="toolbar"><button id="save" class="btn primary">Simpan</button><button id="close" class="btn">Batal</button></div>`);m.querySelector('#close').onclick=()=>m.remove();m.querySelector('#save').onclick=async()=>{let img=p.image||'',f=m.querySelector('#image').files[0];if(f)img=await compressImage(f);let x=p.id?p:{id:uid('p'),active:true};Object.assign(x,{name:val(m,'name'),category:val(m,'category').toUpperCase(),variant:val(m,'variant'),unit:val(m,'unit'),stock:+val(m,'stock'),minStock:+val(m,'minStock'),cost:+val(m,'cost'),price:+val(m,'price'),wholesalePrice:+val(m,'wholesalePrice'),wholesaleMin:+val(m,'wholesaleMin'),aliases:val(m,'aliases'),favorite:m.querySelector('#favorite').checked,image:img});if(!p.id)state.products.unshift(x);log((p.id?'Edit':'Tambah')+' barang: '+x.name);await save('Barang disimpan');m.remove();render()}}
function compressImage(file){return new Promise(res=>{let im=new Image(),r=new FileReader();r.onload=()=>im.src=r.result;im.onload=()=>{let max=900,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=im.width*s;c.height=im.height*s;c.getContext('2d').drawImage(im,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.76))};r.readAsDataURL(file)})}
function download(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;views.products&&render()}});
window.addEventListener('error',e=>{console.error(e.error);toast('Terjadi kesalahan. Data tetap aman.');});
load();
